-- 코드를 작성해주세요
SELECT CASE 
WHEN MONTH(DIFFERENTIATION_DATE) > 9 THEN '4Q'
WHEN MONTH(DIFFERENTIATION_DATE) > 6 THEN '3Q'
WHEN MONTH(DIFFERENTIATION_DATE) > 3 THEN '2Q'
ELSE '1Q'
END AS QUARTER, COUNT(ID) AS ECOLI_COUNT
FROM ECOLI_DATA
GROUP BY QUARTER
ORDER BY QUARTER