-- 코드를 작성해주세요
SELECT A.EMP_NO AS EMP_NO, B.EMP_NAME AS EMP_NAME, 
CASE 
WHEN AVG(A.SCORE) >= 96 THEN 'S'
WHEN AVG(A.SCORE) >= 90 THEN 'A'
WHEN AVG(A.SCORE) >= 80 THEN 'B'
ELSE 'C'
END AS GRADE,
CASE 
WHEN AVG(A.SCORE) >= 96 THEN B.SAL*0.2
WHEN AVG(A.SCORE) >= 90 THEN B.SAL*0.15
WHEN AVG(A.SCORE) >= 80 THEN B.SAL*0.1
ELSE 0
END AS BONUS
FROM HR_GRADE AS A
JOIN HR_EMPLOYEES AS B
ON A.EMP_NO = B.EMP_NO
GROUP BY A.EMP_NO
ORDER BY A.EMP_NO ASC